# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from goto import with_goto
from stddef import *
import var
import pio
import resource
from datetime import datetime

# Peripheral Configuration Code (Do Not Edit)
#---CONFIG_BEGIN---
import cpu
import FileStore
import VFP
import Ports
import Displays
import Generic
import AdafruitHATs

def peripheral_setup () :
# Peripheral Constructors
 pio.cpu=cpu.CPU ()
 pio.storage=FileStore.FileStore ()
 pio.server=VFP.VfpServer ()
 pio.VT1=Ports.SerialTerminal (9600)
 pio.LCD1=Displays.I2CLDC ()
 pio.COUNT=Generic.Button (pio.GPIO4)
 pio.SCAN=Generic.Button (pio.GPIO17)
 pio.BUZ1=Generic.Buzzer (pio.GPIO6)
 pio.LED1=Generic.LED (pio.GPIO19)
 pio.LED2=Generic.LED (pio.GPIO18)
 pio.U2=AdafruitHATs.Adafruit_DC_AND_Stepper_HAT ("0", "0", "0", "0", "0")
 pio.storage.begin ()
 pio.server.begin (0)
# Install interrupt handlers

def peripheral_loop () :
 pass

#---CONFIG_END---
def variables_setup () :
# Flowchart Variables
 var.input = ''
 var.lcd_data = ''
 var.count = 0
 var.tag_1 = ''
 var.tag_2 = ''
 var.tag_3 = ''

# Flowchart Routines
@with_goto
def chart_SETUP () :
 var.tag_1="123456789"; var.tag_2="987654321"; var.tag_3="24810113"
 pio.LCD1.print ("RFID SIMULATION")
 sleep((5))
 return

@with_goto
def chart_LOOP () :
 while not (pio.COUNT()) :
  if pio.SCAN() :
   pio.LCD1.clear ()
   pio.LCD1.print ("SCAN CARD")
   sleep((1000)*0.001)
   pio.LCD1.clear ()
   var.lcd_data = pio.VT1.input (True).strip()
   if not ((var.lcd_data==var.tag_1) or (var.lcd_data==var.tag_2) or (var.lcd_data==var.tag_3)): goto .l20
   pio.LED1.on ()
   pio.LCD1.print ("CHECK DONE")
   sleep((3))
   pio.LED1.off ()
   pio.LCD1.clear ()
   pio.U2.setDcMotor (1, 2, 1)
   sleep((3))
   pio.U2.setDcMotor (1, 0, 0)
   var.count=var.count+1
   goto .l37
   label .l20
   pio.LCD1.print ("invalid card")
   pio.BUZ1.on ()
   pio.LED2.on ()
   sleep((5))
   pio.LED2.off ()
   pio.BUZ1.off ()
   pio.LCD1.clear ()
  
 
 pio.LCD1.clear ()
 pio.LCD1.print ("CHECK ATTENDANCE")
 sleep((1000)*0.001)
 pio.LCD1.clear ()
 pio.LCD1.print ("TOTAL IS: ")
 pio.LCD1.print (var.count)
 sleep((5))
 label .l37
 return

# Main function
def main () :
# Setup
 variables_setup ()
 peripheral_setup ()
 chart_SETUP ()
# Infinite loop
 while True :
  peripheral_loop ()
  chart_LOOP ()
# Command line execution
if __name__ == '__main__' :
   main()
